# Permalinks
permalink:           pretty

# Setup
title:               Richard Hart
tagline:             Software Engineer
url:                 https://www.linkedin.com/in/richard-hart-aa312262
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Richard Hart
  url:               https://twitter.com/r_hart
  email:             richardhart92@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/richardh92/richardh92.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
